// Unit tests for the melee data of zil/1actions.zil:3236-3330, 3606-3801.
//
// The tables are generated by tools/worldgen/melee_tables.py; these tests pin
// their shape and a sample of their text so a regeneration that changed the
// data would fail rather than pass silently.
#include "../src/core/globals.h"
#include "../src/core/object.h"
#include "../src/systems/melee_tables.h"
#include "../src/world/objects.h"
#include "../src/world/world.h"
#include "test_framework.h"

#include <string>

using namespace Melee;

namespace {

/// Renders one melee message the way REMARK does, with fixed stand-in names.
std::string render(const MeleeMsg &msg, const std::string &weapon,
                   const std::string &defender) {
  std::string out;
  for (const auto &part : msg) {
    switch (part.kind) {
    case MeleePart::Weapon: out += weapon; break;
    case MeleePart::Defender: out += defender; break;
    case MeleePart::Text: out += std::string(part.text); break;
    }
  }
  return out;
}

std::size_t countMessages(const std::span<const MeleeResult> &table) {
  std::size_t n = 0;
  for (const auto &row : table) n += row.size();
  return n;
}

} // namespace

// ZIL: the four message tables hold 96 messages between them
// Source: zil/1actions.zil:3611-3800
TEST(MeleeTablesMessageCounts) {
  ASSERT_EQ(HERO_MELEE.size(), static_cast<size_t>(7));
  ASSERT_EQ(CYCLOPS_MELEE.size(), static_cast<size_t>(9));
  ASSERT_EQ(TROLL_MELEE.size(), static_cast<size_t>(9));
  ASSERT_EQ(THIEF_MELEE.size(), static_cast<size_t>(9));

  ASSERT_EQ(countMessages(HERO_MELEE), static_cast<size_t>(29));
  ASSERT_EQ(countMessages(CYCLOPS_MELEE), static_cast<size_t>(14));
  ASSERT_EQ(countMessages(TROLL_MELEE), static_cast<size_t>(25));
  ASSERT_EQ(countMessages(THIEF_MELEE), static_cast<size_t>(28));

  const size_t total = countMessages(HERO_MELEE) + countMessages(CYCLOPS_MELEE) +
                       countMessages(TROLL_MELEE) + countMessages(THIEF_MELEE);
  ASSERT_EQ(total, static_cast<size_t>(96));
}

// ZIL: row index is the blow result less one, so HERO-MELEE row 0 is MISSED
// Source: zil/1actions.zil:3611-3618
TEST(MeleeTablesRowsAreIndexedByResult) {
  const auto missed = HERO_MELEE[static_cast<int>(MISSED) - 1];
  ASSERT_EQ(render(missed[0], "sword", "troll"),
            std::string("Your sword misses the troll by an inch."));
  ASSERT_EQ(render(missed[1], "sword", "troll"),
            std::string("A good slash, but it misses the troll by a mile."));

  const auto killed = HERO_MELEE[static_cast<int>(KILLED) - 1];
  ASSERT_EQ(killed.size(), static_cast<size_t>(3));
  ASSERT_EQ(render(killed[0], "sword", "troll"),
            std::string("It's curtains for the troll as your sword removes his head."));

  // HERO-MELEE stops at LOSE-WEAPON; the hero is never a sitting duck.
  ASSERT_EQ(HERO_MELEE.size(), static_cast<size_t>(static_cast<int>(LOSE_WEAPON)));
}

// ZIL: strings broken across source lines join with a single space
// Source: zil/1actions.zil:3668-3669, 3696-3697
TEST(MeleeTablesJoinContinuationLines) {
  const auto serious = CYCLOPS_MELEE[static_cast<int>(SERIOUS_WOUND) - 1];
  ASSERT_EQ(render(serious[0], "sword", "you"),
            std::string("The monster smashes his huge fist into your chest, "
                        "breaking several ribs."));

  const auto trollOut = TROLL_MELEE[static_cast<int>(UNCONSCIOUS) - 1];
  ASSERT_EQ(render(trollOut[0], "sword", "you"),
            std::string("The flat of the troll's axe hits you delicately on the "
                        "head, knocking you out."));
}

// ZIL: the troll and thief tables carry SITTING-DUCK rows, the hero table does not
// Source: zil/1actions.zil:3733-3734, 3798-3800
TEST(MeleeTablesHaveSittingDuckRows) {
  const auto trollDuck = TROLL_MELEE[static_cast<int>(SITTING_DUCK) - 1];
  ASSERT_EQ(render(trollDuck[0], "sword", "you"),
            std::string("Conquering his fears, the troll puts you to death."));

  const auto cyclopsDuck = CYCLOPS_MELEE[static_cast<int>(SITTING_DUCK) - 1];
  ASSERT_EQ(render(cyclopsDuck[0], "sword", "you"),
            std::string("The Cyclops, no sportsman, dispatches his unconscious victim."));
}

// ZIL: <GLOBAL VILLAINS <LTABLE <TABLE TROLL SWORD 1 0 TROLL-MELEE> ...>>
// Source: zil/1actions.zil:3795-3801
TEST(VillainsTableResolvesToObjects) {
  initializeWorld();
  Melee::resetVillains();

  auto rows = villains();
  ASSERT_EQ(rows.size(), static_cast<size_t>(3));

  ASSERT_EQ(rows[0].villain, ObjectIds::TROLL);
  ASSERT_EQ(rows[0].best, ObjectIds::SWORD);
  ASSERT_EQ(rows[0].bestAdv, 1);
  ASSERT_EQ(rows[0].prob, 0);
  ASSERT_EQ(rows[0].msgs.size(), TROLL_MELEE.size());

  ASSERT_EQ(rows[1].villain, ObjectIds::THIEF);
  ASSERT_EQ(rows[1].best, ObjectIds::KNIFE);
  ASSERT_EQ(rows[1].bestAdv, 1);

  // ZIL: <TABLE CYCLOPS <> 0 0 CYCLOPS-MELEE> - the cyclops has no weapon
  ASSERT_EQ(rows[2].villain, ObjectIds::CYCLOPS);
  ASSERT_EQ(rows[2].best, static_cast<ObjectId>(0));
  ASSERT_EQ(rows[2].bestAdv, 0);

  ASSERT_TRUE(villainFor(ObjectIds::TROLL) != nullptr);
  ASSERT_TRUE(villainFor(ObjectIds::MAILBOX) == nullptr);
}

// ZIL: I-FIGHT writes V-PROB, so the row is mutable state reset by GO
// Source: zil/1actions.zil:3824-3828
TEST(VillainsProbIsMutableAndResets) {
  initializeWorld();
  Melee::resetVillains();

  Villain *troll = villainFor(ObjectIds::TROLL);
  ASSERT_TRUE(troll != nullptr);
  ASSERT_EQ(troll->prob, 0);
  troll->prob = 50;
  ASSERT_EQ(villainFor(ObjectIds::TROLL)->prob, 50);

  Melee::resetVillains();
  ASSERT_EQ(villainFor(ObjectIds::TROLL)->prob, 0);
}

int main() {
  auto results = TestFramework::instance().runAll();
  int failed = 0;
  for (const auto &r : results) {
    if (!r.passed) failed++;
  }
  return failed == 0 ? 0 : 1;
}
