// World initialization - creates all rooms and objects
#include "world.h"
#include "objects.h"
#include "rooms.h"
#include "dungeon.h"
#include "pseudo_actions.h"
#include "zil_loader.h"
#include "core/gglobals.h"
#include "core/globals.h"
#include "core/io.h"
#include "verbs/verbs.h"
#include <memory>

// Forward declarations for action handlers (defined in actions.cpp)
extern bool wonFlag;
int westHouseAction(int rarg);
int trollRoomAction(int rarg);
int northHouseAction(int rarg);
int southHouseAction(int rarg);
int behindHouseAction(int rarg);
int stoneBarrowAction(int rarg);
int mazeRoomAction(int rarg);
bool mailboxAction();
bool trophyCaseAction();
bool coffinAction();
bool basketAction();
bool sackAction();
bool bagAction();
bool bottleAction();
bool whiteHouseAction();
bool boardAction();
extern bool kitchenAction();
bool forestAction();
bool rugAction();
bool groundAction();
bool kitchenWindowAction();
int swordAction();
int lampAction();
bool ropeAction();
bool wrenchAction();
bool screwdriverAction();
bool shovelAction();
bool torchAction();
int candlesAction();
int matchesAction();
bool paintingAction();
bool eggAction();
bool canaryAction();
bool boatAction();
bool pumpAction();
bool machineAction();
bool mirrorAction();
bool damAction();
int damRoomAction(int rarg);
int deepCanyonRoomAction(int rarg); // DEEP-CANYON-F
bool inflatableBoatAction(); // IBOAT-FUNCTION
bool puncturedBoatAction(); // DBOAT-FUNCTION
bool boltAction();
bool bubbleAction();
bool buttonAction();
bool gunkAction();
// Batch 3 Actions
bool bagOfCoinsAction();
bool trunkAction();
bool axeAction();

void initializeWorld() {
    auto& g = Globals::instance();

    // ZIL: every <ROOM> and <OBJECT> of 1dungeon.zil and gglobals.zil,
    // built from the data generated by tools/worldgen.
    // Source: zil/1dungeon.zil, zil/gglobals.zil
    ZilLoader::loadRooms();
    ZilLoader::loadObjects();

    g.score = 0;
    g.moves = 0;
}
