// World initialization - creates all rooms and objects
#include "world.h"
#include "objects.h"
#include "rooms.h"
#include "world_objects.h"
#include "dungeon.h"
#include "pseudo_actions.h"
#include "zil_loader.h"
#include "core/gglobals.h"
#include "core/globals.h"
#include "core/io.h"
#include "verbs/verbs.h"
#include "systems/npc.h"
#include "systems/candle.h"
#include <memory>

// Forward declarations for action handlers (defined in actions.cpp)
extern bool wonFlag;
int westHouseAction(int rarg);
int trollRoomAction(int rarg);
int northHouseAction(int rarg);
int southHouseAction(int rarg);
int behindHouseAction(int rarg);
int stoneBarrowAction(int rarg);
int mazeRoomAction(int rarg);
bool mailboxAction();
bool trophyCaseAction();
bool coffinAction();
bool basketAction();
bool sackAction();
bool bagAction();
bool bottleAction();
bool whiteHouseAction();
bool boardAction();
extern bool kitchenAction();
bool forestAction();
bool rugAction();
bool groundAction();
bool kitchenWindowAction();
bool swordAction();
bool lampAction();
bool ropeAction();
bool wrenchAction();
bool screwdriverAction();
bool shovelAction();
bool torchAction();
bool candlesAction();
bool matchesAction();
bool paintingAction();
bool eggAction();
bool canaryAction();
bool boatAction();
bool pumpAction();
bool machineAction();
bool mirrorAction();
bool damAction();
int damRoomAction(int rarg);
int deepCanyonRoomAction(int rarg); // DEEP-CANYON-F
bool inflatableBoatAction(); // IBOAT-FUNCTION
bool puncturedBoatAction(); // DBOAT-FUNCTION
bool boltAction();
bool bubbleAction();
bool buttonAction();
bool gunkAction();
// Batch 3 Actions
bool bagOfCoinsAction();
bool trunkAction();
bool axeAction();

void initializeWorld() {
    auto& g = Globals::instance();
    
    // ZIL: every <ROOM> of 1dungeon.zil, built from the data generated by
    // tools/worldgen.  Source: zil/1dungeon.zil:1239-2619
    ZilLoader::loadRooms();

    // ===== SPECIAL AREA ROOMS =====
    
    // Create Mailbox object
    auto mailbox = std::make_unique<ZObject>(OBJ_MAILBOX, "small mailbox");
    mailbox->addSynonym("mailbox");
    mailbox->addSynonym("box");
    mailbox->addAdjective("small");
    mailbox->setFlag(ObjectFlag::CONTBIT);
    mailbox->setFlag(ObjectFlag::TRYTAKEBIT);
    mailbox->setProperty(P_CAPACITY, 10);
    mailbox->setAction(mailboxAction);
    mailbox->moveTo(g.getObject(ROOM_WEST_OF_HOUSE));
    
    g.registerObject(OBJ_MAILBOX, std::move(mailbox));
    
    // Create LEAFLET (Advertisement) - readable object
    auto leaflet = std::make_unique<ZObject>(ObjectIds::ADVERTISEMENT, "leaflet");
    leaflet->addSynonym("leaflet");
    leaflet->addSynonym("advertisement");
    leaflet->addSynonym("mail");
    leaflet->addSynonym("booklet");
    leaflet->addSynonym("pamphlet");
    leaflet->setFlag(ObjectFlag::TAKEBIT);
    leaflet->setFlag(ObjectFlag::READBIT);
    leaflet->setFlag(ObjectFlag::BURNBIT);
    leaflet->setProperty(P_SIZE, 2);
    leaflet->setText(
        "\"WELCOME TO ZORK!\n\n"
        "ZORK is a game of adventure, danger, and low cunning. In it you\n"
        "will explore some of the most amazing territory ever seen by\n"
        "mortals. No computer should be without one!\""
    );
    leaflet->setLongDesc("A small leaflet is on the ground.");
    leaflet->moveTo(g.getObject(OBJ_MAILBOX));  // Initially in mailbox
    
    g.registerObject(ObjectIds::ADVERTISEMENT, std::move(leaflet));
    
    // Create BOOK (Black book) - readable object
    auto book = std::make_unique<ZObject>(ObjectIds::BOOK, "black book");
    book->addSynonym("book");
    book->addSynonym("tome");
    book->addAdjective("black");
    book->setFlag(ObjectFlag::TAKEBIT);
    book->setFlag(ObjectFlag::READBIT);
    book->setFlag(ObjectFlag::BURNBIT);
    book->setProperty(P_SIZE, 5);
    book->setText(
        "Commandment #12592\n\n"
        "Oh ye who go about saying unto each: 'Hello sailor':\n"
        "Dost thou know the magnitude of thy sin before the gods?\n"
        "Yea, verily, thou shalt be ground between two stones.\n"
        "Shall the angry gods cast thy body into the whirlpool?\n"
        "Surely, thy eye shall be put out with a sharp stick!\n"
        "Even unto the ends of the earth shalt thou wander and\n"
        "Unto the land of the dead shalt thou be sent at last.\n"
        "Surely thou shalt repent of thy cunning."
    );
    // Book location will be set when we know where it should be placed
    // For now, let's put it in the library or a similar location
    // book->moveTo(g.getObject(RoomIds::LIBRARY));  // TODO: Set proper location
    
    g.registerObject(ObjectIds::BOOK, std::move(book));
    
    // Create GUIDE (Tour guidebook) - readable object
    auto guide = std::make_unique<ZObject>(ObjectIds::GUIDE, "tour guidebook");
    guide->addSynonym("guide");
    guide->addSynonym("guidebook");
    guide->addSynonym("book");
    guide->addAdjective("tour");
    guide->setFlag(ObjectFlag::TAKEBIT);
    guide->setFlag(ObjectFlag::READBIT);
    guide->setFlag(ObjectFlag::BURNBIT);
    guide->setProperty(P_SIZE, 3);
    guide->setText(
        "Flood Control Dam #3\n\n"
        "FCD#3 was constructed in year 783 of the Great Underground Empire to harness the mighty Frigid River. This work was supported by a grant of 37 million zorkmids from your omnipotent local tyrant Lord Dimwit Flathead the Excessive. This impressive structure is composed of 370,000 cubic feet of concrete, is 256 feet tall at the center, and 193 feet wide at the top. The reservoir created behind the dam has a volume of 1.7 billion cubic feet, an area of 12 million square feet, and a shore line of 36 thousand feet.\n\n"
        "The construction of FCD#3 took 112 days from ground breaking to the dedication. It required a work force of 384 slaves, 34 slave drivers, 12 engineers, 2 turtle doves, and a partridge in a pear tree. The work was managed by a command team composed of 2345 bureaucrats, 2347 secretaries (at least two of whom could type), 12,256 paper shufflers, 52,469 rubber stampers, 245,193 red tape processors, and nearly one million dead trees.\n\n"
        "We will now point out some of the more interesting features of FCD#3 as we conduct you on a guided tour of the facilities..."
    );
    // Guide location will be set when we know where it should be placed
    // guide->moveTo(g.getObject(RoomIds::DAM_LOBBY));  // TODO: Set proper location
    
    g.registerObject(ObjectIds::GUIDE, std::move(guide));
    
    // Create OWNERS_MANUAL (Owner's manual) - readable object
    auto ownersManual = std::make_unique<ZObject>(ObjectIds::OWNERS_MANUAL, "owner's manual");
    ownersManual->addSynonym("manual");
    ownersManual->addSynonym("book");
    ownersManual->addAdjective("owners");
    ownersManual->addAdjective("owner's");
    ownersManual->setFlag(ObjectFlag::TAKEBIT);
    ownersManual->setFlag(ObjectFlag::READBIT);
    ownersManual->setFlag(ObjectFlag::BURNBIT);
    ownersManual->setProperty(P_SIZE, 3);
    ownersManual->setText(
        "Congratulations! You are the proud owner of a FROBOZZ MAGIC BOAT, the finest boat in the world. Your boat is guaranteed against all defects for a period of 76 years. If you have any questions about the operation of your boat, please consult your local dealer."
    );
    // Manual location will be set when we know where it should be placed
    // ownersManual->moveTo(g.getObject(RoomIds::BOAT_LOCATION));  // TODO: Set proper location
    
    g.registerObject(ObjectIds::OWNERS_MANUAL, std::move(ownersManual));
    
    // Create MAP (Map) - readable object
    auto map = std::make_unique<ZObject>(ObjectIds::MAP, "map");
    map->addSynonym("map");
    map->addSynonym("chart");
    map->setFlag(ObjectFlag::TAKEBIT);
    map->setFlag(ObjectFlag::READBIT);
    map->setFlag(ObjectFlag::BURNBIT);
    map->setProperty(P_SIZE, 2);
    map->setText(
        "The map shows a complex maze of twisty passages, all alike."
    );
    // Map location will be set when we know where it should be placed
    // map->moveTo(g.getObject(RoomIds::MAZE_ENTRANCE));  // TODO: Set proper location
    
    g.registerObject(ObjectIds::MAP, std::move(map));
    
    // Create BOAT_LABEL (Label on boat) - readable object
    auto boatLabel = std::make_unique<ZObject>(ObjectIds::BOAT_LABEL, "label");
    boatLabel->addSynonym("label");
    boatLabel->addSynonym("tag");
    boatLabel->setFlag(ObjectFlag::READBIT);
    boatLabel->setFlag(ObjectFlag::TRYTAKEBIT);  // Cannot be taken (attached to boat)
    boatLabel->setProperty(P_SIZE, 1);
    boatLabel->setText(
        "FROBOZZ MAGIC BOAT COMPANY\n"
        "  Inflatable Boat\n"
        "  Capacity: 2\n"
        "  Model: FMB-1\n"
        "  Serial Number: 123456789"
    );
    // Label location will be set when boat is created
    // boatLabel->moveTo(g.getObject(ObjectIds::BOAT_INFLATABLE));  // TODO: Set proper location
    
    g.registerObject(ObjectIds::BOAT_LABEL, std::move(boatLabel));
    
    // Create Trophy Case container
    auto trophyCase = std::make_unique<ZObject>(ObjectIds::TROPHY_CASE, "trophy case");
    trophyCase->addSynonym("case");
    trophyCase->addAdjective("trophy");
    trophyCase->setFlag(ObjectFlag::CONTBIT);
    trophyCase->setFlag(ObjectFlag::TRANSBIT);  // Transparent - can see contents
    trophyCase->setFlag(ObjectFlag::OPENBIT);   // Initially open
    trophyCase->setFlag(ObjectFlag::TRYTAKEBIT); // Cannot be taken (anchored)
    trophyCase->setFlag(ObjectFlag::NDESCBIT);   // Don't describe separately
    trophyCase->setFlag(ObjectFlag::SEARCHBIT);  // Can be searched
    trophyCase->setProperty(P_CAPACITY, 10000);  // Large capacity for treasures
    trophyCase->setAction(trophyCaseAction);
    trophyCase->moveTo(g.getObject(RoomIds::LIVING_ROOM));
    
    g.registerObject(ObjectIds::TROPHY_CASE, std::move(trophyCase));
    
    // Create SACK (Brown sack/sandwich bag) - portable container
    auto sack = std::make_unique<ZObject>(ObjectIds::SACK, "brown sack");
    sack->addSynonym("sack");
    sack->addSynonym("bag");
    sack->addAdjective("brown");
    sack->addAdjective("elongated");
    sack->addAdjective("smelly");
    sack->setFlag(ObjectFlag::TAKEBIT);
    sack->setFlag(ObjectFlag::CONTBIT);
    sack->setFlag(ObjectFlag::OPENBIT);    // Initially open
    sack->setFlag(ObjectFlag::BURNBIT);    // Can be burned
    sack->setProperty(P_CAPACITY, 9);
    sack->setProperty(P_SIZE, 9);
    sack->setAction(sackAction);
    sack->setLongDesc("On the table is an elongated brown sack, smelling of hot peppers.");
    sack->moveTo(g.getObject(RoomIds::KITCHEN));  // On kitchen table
    
    g.registerObject(ObjectIds::SACK, std::move(sack));
    
    // Create LUNCH (Hot pepper sandwich) - food item inside sack
    auto lunch = std::make_unique<ZObject>(ObjectIds::LUNCH, "lunch");
    lunch->addSynonym("lunch");
    lunch->addSynonym("sandwich");
    lunch->addSynonym("pepper");
    lunch->addAdjective("hot");
    lunch->addAdjective("pepper");
    lunch->setFlag(ObjectFlag::TAKEBIT);
    lunch->setFlag(ObjectFlag::FOODBIT);
    lunch->setProperty(P_SIZE, 4);
    lunch->setLongDesc("A hot pepper sandwich is here.");
    lunch->moveTo(g.getObject(ObjectIds::SACK));  // Inside the sack
    g.registerObject(ObjectIds::LUNCH, std::move(lunch));
    
    // Create GARLIC (Clove of garlic) - food item inside sack
    auto garlic = std::make_unique<ZObject>(ObjectIds::GARLIC, "clove of garlic");
    garlic->addSynonym("garlic");
    garlic->addSynonym("clove");
    garlic->setFlag(ObjectFlag::TAKEBIT);
    garlic->setFlag(ObjectFlag::FOODBIT);
    garlic->setProperty(P_SIZE, 2);
    garlic->moveTo(g.getObject(ObjectIds::SACK));  // Inside the sack
    g.registerObject(ObjectIds::GARLIC, std::move(garlic));
    
    // Create BAG (Large bag - thief's bag) - portable container
    auto bag = std::make_unique<ZObject>(ObjectIds::BAG, "large bag");
    bag->addSynonym("bag");
    bag->addSynonym("sack");
    bag->addAdjective("large");
    bag->setFlag(ObjectFlag::TAKEBIT);
    bag->setFlag(ObjectFlag::CONTBIT);
    bag->setFlag(ObjectFlag::OPENBIT);     // Initially open
    bag->setProperty(P_CAPACITY, 100);     // Large capacity (thief's bag)
    bag->setProperty(P_SIZE, 20);
    g.registerObject(ObjectIds::BAG, std::move(bag));

    // Create BAG_OF_COINS
    auto bagOfCoins = std::make_unique<ZObject>(ObjectIds::BAG_OF_COINS, "bag of coins");
    bagOfCoins->addSynonym("bag");
    bagOfCoins->addSynonym("coins");
    bagOfCoins->addAdjective("old");
    bagOfCoins->addAdjective("leather");
    bagOfCoins->setFlag(ObjectFlag::TAKEBIT);
    bagOfCoins->setFlag(ObjectFlag::CONTBIT); // It contains coins, but maybe just treated as opaque object? ZIL says STUPID-CONTAINER.
    bagOfCoins->setProperty(P_SIZE, 15);
    bagOfCoins->setProperty(P_VALUE, 10); // Treasure value
    bagOfCoins->setAction(bagOfCoinsAction);
    
    // Initial location? Usually in Maze or with Thief?
    // ZIL: "bag of coins" IN "maze" (Room MAZE-11?) or Thief has it?
    // Zork1 Logic: Thief has it initially or drops it. 
    // For now, place in a maze room or leave null to be placed by Thief logic.
    // Let's place it in MAZE_5 (placeholder) or define initial location.
    
    g.registerObject(ObjectIds::BAG_OF_COINS, std::move(bagOfCoins));
    
    // Create RAISED_BASKET (Basket at top of shaft) - special container
    auto raisedBasket = std::make_unique<ZObject>(ObjectIds::RAISED_BASKET, "basket");
    raisedBasket->addSynonym("basket");
    raisedBasket->addSynonym("cage");
    raisedBasket->addSynonym("dumbwaiter");
    raisedBasket->setFlag(ObjectFlag::CONTBIT);
    raisedBasket->setFlag(ObjectFlag::TRANSBIT);  // Transparent
    raisedBasket->setFlag(ObjectFlag::OPENBIT);   // Open
    raisedBasket->setFlag(ObjectFlag::TRYTAKEBIT); // Cannot be taken
    raisedBasket->setProperty(P_CAPACITY, 50);
    raisedBasket->setAction(basketAction);
    raisedBasket->moveTo(g.getObject(RoomIds::SHAFT_ROOM));
    
    g.registerObject(ObjectIds::RAISED_BASKET, std::move(raisedBasket));
    
    // Create LOWERED_BASKET (Basket at bottom of shaft) - special container
    auto loweredBasket = std::make_unique<ZObject>(ObjectIds::BASKET, "basket");
    loweredBasket->addSynonym("basket");
    loweredBasket->addSynonym("cage");
    loweredBasket->addSynonym("dumbwaiter");
    loweredBasket->addAdjective("lowered");
    loweredBasket->setFlag(ObjectFlag::TRYTAKEBIT); // Cannot be taken
    // Note: This basket is not a container when lowered - it becomes one when raised
    loweredBasket->setAction(basketAction);
    loweredBasket->moveTo(g.getObject(RoomIds::LOWER_SHAFT));
    
    g.registerObject(ObjectIds::BASKET, std::move(loweredBasket));
    
    // Create BUOY (Red buoy - portable container) (ZIL: 1dungeon.zil:782-796)
    auto buoy = std::make_unique<ZObject>(ObjectIds::BUOY, "red buoy");
    buoy->addSynonym("buoy");
    buoy->addAdjective("red");
    buoy->setFlag(ObjectFlag::TAKEBIT);
    buoy->setFlag(ObjectFlag::CONTBIT);
    buoy->setFlag(ObjectFlag::SEARCHBIT);
    buoy->setProperty(P_CAPACITY, 20);
    buoy->setProperty(P_SIZE, 10);
    buoy->setFirstDesc("There is a red buoy here (probably a warning).");
    buoy->setAction(Dungeon::treasureInsideAction);
    buoy->moveTo(g.getObject(RoomIds::RIVER_4));
    
    g.registerObject(ObjectIds::BUOY, std::move(buoy));
    
    // Create NEST (Bird's nest - portable container)
    auto nest = std::make_unique<ZObject>(ObjectIds::NEST, "bird's nest");
    nest->addSynonym("nest");
    nest->addAdjective("birds");
    nest->setFlag(ObjectFlag::TAKEBIT);
    nest->setFlag(ObjectFlag::CONTBIT);
    nest->setFlag(ObjectFlag::OPENBIT);
    nest->setFlag(ObjectFlag::BURNBIT);
    nest->setFlag(ObjectFlag::SEARCHBIT);
    nest->setProperty(P_SIZE, 5);  // Requirement 63.1
    nest->setProperty(P_CAPACITY, 20);
    // TODO: Add action handler
    nest->moveTo(g.getObject(RoomIds::UP_A_TREE));
    
    g.registerObject(ObjectIds::NEST, std::move(nest));
    
    // Create TOOL_CHEST (Group of tool chests - anchored container)
    auto toolChest = std::make_unique<ZObject>(ObjectIds::TOOL_CHEST, "group of tool chests");
    toolChest->addSynonym("chest");
    toolChest->addSynonym("chests");
    toolChest->addSynonym("group");
    toolChest->addSynonym("toolchests");
    toolChest->addAdjective("tool");
    toolChest->setFlag(ObjectFlag::CONTBIT);
    toolChest->setFlag(ObjectFlag::OPENBIT);
    toolChest->setFlag(ObjectFlag::TRYTAKEBIT);  // Cannot be taken
    toolChest->setFlag(ObjectFlag::SACREDBIT);
    toolChest->setProperty(P_CAPACITY, 40);  // Moderate capacity for tools
    // TODO: Add action handler
    // Will be placed in Maintenance Room when that room is created
    
    g.registerObject(ObjectIds::TOOL_CHEST, std::move(toolChest));
    
    // Create ALTAR (Altar - surface container)
    auto altar = std::make_unique<ZObject>(ObjectIds::ALTAR, "altar");
    altar->addSynonym("altar");
    altar->setFlag(ObjectFlag::CONTBIT);
    altar->setFlag(ObjectFlag::OPENBIT);
    altar->setFlag(ObjectFlag::SURFACEBIT);
    altar->setFlag(ObjectFlag::NDESCBIT);
    altar->setProperty(P_CAPACITY, 50);
    // TODO: Add action handler
    // Will be placed in South Temple when that room is created
    
    g.registerObject(ObjectIds::ALTAR, std::move(altar));
    
    // Create PEDESTAL (White marble pedestal - surface container)
    auto pedestal = std::make_unique<ZObject>(ObjectIds::PEDESTAL, "pedestal");
    pedestal->addSynonym("pedestal");
    pedestal->addAdjective("white");
    pedestal->addAdjective("marble");
    pedestal->setFlag(ObjectFlag::CONTBIT);
    pedestal->setFlag(ObjectFlag::OPENBIT);
    pedestal->setFlag(ObjectFlag::SURFACEBIT);
    pedestal->setFlag(ObjectFlag::NDESCBIT);
    pedestal->setProperty(P_CAPACITY, 30);
    // TODO: Add action handler
    // Will be placed in Torch Room when that room is created
    
    g.registerObject(ObjectIds::PEDESTAL, std::move(pedestal));
    
    // Create White House global object
    auto whiteHouse = std::make_unique<ZObject>(OBJ_WHITE_HOUSE, "white house");
    whiteHouse->addSynonym("house");
    whiteHouse->addAdjective("white");
    whiteHouse->addAdjective("beautiful");
    whiteHouse->addAdjective("colonial");
    whiteHouse->setFlag(ObjectFlag::NDESCBIT);
    whiteHouse->setAction(whiteHouseAction);
    
    g.registerObject(OBJ_WHITE_HOUSE, std::move(whiteHouse));
    
    // Create Board global object
    auto board = std::make_unique<ZObject>(OBJ_BOARD, "board");
    board->addSynonym("boards");
    board->addSynonym("board");
    board->setFlag(ObjectFlag::NDESCBIT);
    board->setAction(boardAction);
    
    g.registerObject(OBJ_BOARD, std::move(board));
    
    // Create Forest global object
    auto forest = std::make_unique<ZObject>(OBJ_FOREST, "forest");
    forest->addSynonym("forest");
    forest->addSynonym("trees");
    forest->addSynonym("pines");
    forest->addSynonym("hemlocks");
    forest->setFlag(ObjectFlag::NDESCBIT);
    forest->setAction(forestAction);
    
    g.registerObject(OBJ_FOREST, std::move(forest));
    
    // Create Kitchen Window global object
    auto kitchenWindow = std::make_unique<ZObject>(OBJ_KITCHEN_WINDOW, "kitchen window");
    kitchenWindow->addSynonym("window");
    kitchenWindow->addAdjective("kitchen");
    kitchenWindow->addAdjective("small");
    kitchenWindow->setFlag(ObjectFlag::NDESCBIT);
    kitchenWindow->setFlag(ObjectFlag::DOORBIT);
    kitchenWindow->setAction(kitchenWindowAction);
    
    g.registerObject(OBJ_KITCHEN_WINDOW, std::move(kitchenWindow));
    
    // GROUND is created by GGlobals::initGlobalObjects (gglobals.zil:164-168).

    // Create Hands global object (ZIL: HANDS in GLOBAL-OBJECTS)
    auto hands = std::make_unique<ZObject>(ObjectIds::HANDS, "pair of hands");
    hands->addSynonym("pair");
    hands->addSynonym("hands");
    hands->addSynonym("hand");
    hands->addAdjective("bare");
    hands->setFlag(ObjectFlag::NDESCBIT);
    hands->setFlag(ObjectFlag::TOOLBIT);
    g.registerObject(ObjectIds::HANDS, std::move(hands));
    
    // Create Adventurer object (Task 24.1: Initialize player state)
    auto adventurer = std::make_unique<ZObject>(OBJ_ADVENTURER, "adventurer");
    adventurer->addSynonym("adventurer");
    adventurer->addSynonym("me");
    adventurer->addSynonym("myself");
    adventurer->addSynonym("self");
    adventurer->setFlag(ObjectFlag::NDESCBIT);
    adventurer->setFlag(ObjectFlag::INVISIBLE);
    adventurer->setFlag(ObjectFlag::SACREDBIT);
    adventurer->setFlag(ObjectFlag::ACTORBIT);
    adventurer->setProperty(P_STRENGTH, 10);  // Player strength
    // Player starts at West of House (g.here is already set to WEST_OF_HOUSE)
    adventurer->moveTo(g.here);
    
    g.winner = adventurer.get();
    g.player = adventurer.get();
    g.registerObject(OBJ_ADVENTURER, std::move(adventurer));
    
    // ===== TREASURE OBJECTS =====
    
    // Create TROPHY (Zorkmid trophy)
    auto trophy = std::make_unique<ZObject>(ObjectIds::TROPHY, "trophy");
    trophy->addSynonym("trophy");
    trophy->addSynonym("cup");
    trophy->addAdjective("large");
    trophy->addAdjective("zorkmid");
    trophy->setFlag(ObjectFlag::TAKEBIT);
    trophy->setProperty(P_VALUE, 5);
    trophy->setProperty(P_TVALUE, 5);
    trophy->setProperty(P_SIZE, 5);
    trophy->moveTo(g.getObject(RoomIds::TREASURE_ROOM));
    g.registerObject(ObjectIds::TROPHY, std::move(trophy));
    
    // Create EGG (Jewel-encrusted egg) - starts CLOSED, contains canary
    auto egg = std::make_unique<ZObject>(ObjectIds::EGG, "jewel-encrusted egg");
    egg->addSynonym("egg");
    egg->addSynonym("treasure");
    egg->addAdjective("jewel");
    egg->addAdjective("jeweled");
    egg->addAdjective("encrusted");
    egg->addAdjective("birds");
    egg->setFlag(ObjectFlag::TAKEBIT);
    egg->setFlag(ObjectFlag::CONTBIT);
    egg->setFlag(ObjectFlag::SEARCHBIT);
    // Note: Egg starts CLOSED (no OPENBIT) - must be opened carefully
    egg->setProperty(P_VALUE, 5);
    egg->setProperty(P_TVALUE, 5);
    egg->setProperty(P_SIZE, 5);
    egg->setProperty(P_CAPACITY, 6);
    egg->setAction(eggAction);
    egg->setFirstDesc("In the bird's nest is a large egg encrusted with precious jewels, apparently scavenged by a childless songbird. The egg is covered with fine gold inlay, and ornamented in lapis lazuli and mother-of-pearl. Unlike most eggs, this one is hinged and closed with a delicate looking clasp. The egg appears extremely fragile.");
    // Egg will be placed in nest after nest is created
    g.registerObject(ObjectIds::EGG, std::move(egg));
    
    // Create BROKEN_EGG (Broken jewel-encrusted egg) - created when egg is damaged
    auto brokenEgg = std::make_unique<ZObject>(ObjectIds::BROKEN_EGG, "broken jewel-encrusted egg");
    brokenEgg->addSynonym("egg");
    brokenEgg->addSynonym("treasure");
    brokenEgg->addAdjective("broken");
    brokenEgg->addAdjective("birds");
    brokenEgg->addAdjective("encrusted");
    brokenEgg->addAdjective("jewel");
    brokenEgg->setFlag(ObjectFlag::TAKEBIT);
    brokenEgg->setFlag(ObjectFlag::CONTBIT);
    brokenEgg->setFlag(ObjectFlag::OPENBIT);  // Broken egg is always open
    brokenEgg->setProperty(P_TVALUE, 2);  // Worth less than intact egg
    brokenEgg->setProperty(P_SIZE, 5);
    brokenEgg->setProperty(P_CAPACITY, 6);
    brokenEgg->setText("There is a somewhat ruined egg here.");
    brokenEgg->setLongDesc("There is a somewhat ruined egg here.");
    // Broken egg starts nowhere - created when egg is damaged
    g.registerObject(ObjectIds::BROKEN_EGG, std::move(brokenEgg));
    
    // Create CANARY (Golden clockwork canary) - inside the egg
    auto canary = std::make_unique<ZObject>(ObjectIds::CANARY, "golden clockwork canary");
    canary->addSynonym("canary");
    canary->addSynonym("treasure");
    canary->addAdjective("clockwork");
    canary->addAdjective("gold");
    canary->addAdjective("golden");
    canary->setFlag(ObjectFlag::TAKEBIT);
    canary->setFlag(ObjectFlag::SEARCHBIT);
    canary->setProperty(P_VALUE, 6);
    canary->setProperty(P_TVALUE, 4);
    canary->setProperty(P_SIZE, 3);
    canary->setAction(canaryAction);
    canary->setFirstDesc("There is a golden clockwork canary nestled in the egg. It has ruby eyes and a silver beak. Through a crystal window below its left wing you can see intricate machinery inside. It appears to have wound down.");
    // Canary will be placed in egg after egg is registered
    g.registerObject(ObjectIds::CANARY, std::move(canary));
    
    // Now place canary in egg (after both are registered)
    ZObject* eggObj = g.getObject(ObjectIds::EGG);
    ZObject* canaryObj = g.getObject(ObjectIds::CANARY);
    if (eggObj && canaryObj) {
        canaryObj->moveTo(eggObj);
    }
    
    // Place egg in UP_A_TREE room (in the nest - nest is scenery)
    if (eggObj) {
        eggObj->moveTo(g.getObject(RoomIds::UP_A_TREE));
    }
    
    // Create BROKEN_CANARY (Broken clockwork canary) - created when egg is damaged with canary inside
    auto brokenCanary = std::make_unique<ZObject>(ObjectIds::BROKEN_CANARY, "broken clockwork canary");
    brokenCanary->addSynonym("canary");
    brokenCanary->addSynonym("treasure");
    brokenCanary->addAdjective("broken");
    brokenCanary->addAdjective("clockwork");
    brokenCanary->addAdjective("gold");
    brokenCanary->addAdjective("golden");
    brokenCanary->setFlag(ObjectFlag::TAKEBIT);
    brokenCanary->setProperty(P_TVALUE, 1);  // Worth much less than intact canary
    brokenCanary->setProperty(P_SIZE, 3);
    brokenCanary->setAction(canaryAction);
    brokenCanary->setFirstDesc("There is a golden clockwork canary nestled in the egg. It seems to have recently had a bad experience. The mountings for its jewel-like eyes are empty, and its silver beak is crumpled. Through a cracked crystal window below its left wing you can see the remains of intricate machinery. It is not clear what result winding it would have, as the mainspring seems sprung.");
    // Broken canary starts in broken egg (but broken egg starts nowhere)
    brokenCanary->moveTo(g.getObject(ObjectIds::BROKEN_EGG));
    g.registerObject(ObjectIds::BROKEN_CANARY, std::move(brokenCanary));
    
    // Create BAUBLE (Beautiful brass bauble) - produced by winding canary in forest
    auto bauble = std::make_unique<ZObject>(ObjectIds::BAUBLE, "beautiful brass bauble");
    bauble->addSynonym("bauble");
    bauble->addSynonym("treasure");
    bauble->addAdjective("brass");
    bauble->addAdjective("beautiful");
    bauble->setFlag(ObjectFlag::TAKEBIT);
    bauble->setProperty(P_VALUE, 1);
    bauble->setProperty(P_TVALUE, 1);
    bauble->setProperty(P_SIZE, 2);
    // Bauble starts nowhere - produced by winding canary in forest
    g.registerObject(ObjectIds::BAUBLE, std::move(bauble));
    
    // Create CHALICE (Chalice)
    auto chalice = std::make_unique<ZObject>(ObjectIds::CHALICE, "silver chalice");
    chalice->addSynonym("chalice");
    chalice->addSynonym("goblet");
    chalice->addSynonym("grail");
    chalice->addSynonym("cup");
    chalice->addSynonym("treasure");
    chalice->addAdjective("silver");
    chalice->setFlag(ObjectFlag::TAKEBIT);
    chalice->setFlag(ObjectFlag::CONTBIT);
    chalice->setProperty(P_VALUE, 10);
    chalice->setProperty(P_TVALUE, 5);
    chalice->setProperty(P_SIZE, 10);
    chalice->setProperty(P_CAPACITY, 5);
    chalice->setLongDesc("There is a silver chalice, intricately engraved, here.");
    chalice->moveTo(g.getObject(RoomIds::TREASURE_ROOM));
    g.registerObject(ObjectIds::CHALICE, std::move(chalice));
    
    // Create TRIDENT (Crystal trident)
    auto trident = std::make_unique<ZObject>(ObjectIds::TRIDENT, "crystal trident");
    trident->addSynonym("trident");
    trident->addSynonym("fork");
    trident->addSynonym("treasure");
    trident->addAdjective("crystal");
    trident->addAdjective("poseidon");
    trident->setFlag(ObjectFlag::TAKEBIT);
    trident->setFlag(ObjectFlag::WEAPONBIT);
    trident->setProperty(P_VALUE, 4);
    trident->setProperty(P_TVALUE, 11);
    trident->setProperty(P_SIZE, 20);
    trident->moveTo(g.getObject(RoomIds::ATLANTIS_ROOM));
    g.registerObject(ObjectIds::TRIDENT, std::move(trident));
    
    // Create JEWELS (Trunk of jewels)
    auto jewels = std::make_unique<ZObject>(ObjectIds::JEWELS, "trunk of jewels");
    jewels->addSynonym("jewels");
    jewels->addSynonym("trunk");
    jewels->addSynonym("jewelry");
    jewels->addSynonym("gems");
    jewels->addSynonym("treasure");
    jewels->addAdjective("precious");
    jewels->addAdjective("old");
    jewels->setFlag(ObjectFlag::TAKEBIT);
    jewels->setFlag(ObjectFlag::INVISIBLE);
    jewels->setProperty(P_VALUE, 15);
    jewels->setProperty(P_TVALUE, 5);
    jewels->setProperty(P_SIZE, 35);
    jewels->setLongDesc("There is an old trunk here, bulging with assorted jewels.");
    jewels->moveTo(g.getObject(RoomIds::RESERVOIR));
    g.registerObject(ObjectIds::JEWELS, std::move(jewels));
    
    // Create COINS (Bag of coins)
    auto coins = std::make_unique<ZObject>(ObjectIds::COINS, "bag of coins");
    coins->addSynonym("coins");
    coins->addSynonym("bag");
    coins->addSynonym("coin");
    coins->addSynonym("zorkmids");
    coins->addSynonym("treasure");
    coins->addAdjective("leather");
    coins->addAdjective("large");
    coins->setFlag(ObjectFlag::TAKEBIT);
    coins->setProperty(P_VALUE, 10);
    coins->setProperty(P_TVALUE, 5);
    coins->setProperty(P_SIZE, 15);
    coins->setLongDesc("An old leather bag, bulging with coins, is here.");
    coins->moveTo(g.getObject(RoomIds::MAZE_5));
    g.registerObject(ObjectIds::COINS, std::move(coins));
    
    // Create DIAMOND (Huge diamond)
    auto diamond = std::make_unique<ZObject>(ObjectIds::DIAMOND, "huge diamond");
    diamond->addSynonym("diamond");
    diamond->addSynonym("gem");
    diamond->addSynonym("treasure");
    diamond->addAdjective("huge");
    diamond->addAdjective("enormous");
    diamond->setFlag(ObjectFlag::TAKEBIT);
    diamond->setProperty(P_VALUE, 10);
    diamond->setProperty(P_TVALUE, 10);
    diamond->setProperty(P_SIZE, 5);
    diamond->setLongDesc("There is an enormous diamond (perfectly cut) here.");
    // Dynamic - appears when thief is defeated
    g.registerObject(ObjectIds::DIAMOND, std::move(diamond));
    
    // Create EMERALD (Large emerald)
    auto emerald = std::make_unique<ZObject>(ObjectIds::EMERALD, "large emerald");
    emerald->addSynonym("emerald");
    emerald->addSynonym("gem");
    emerald->addSynonym("treasure");
    emerald->addAdjective("large");
    emerald->setFlag(ObjectFlag::TAKEBIT);
    emerald->setProperty(P_VALUE, 5);
    emerald->setProperty(P_TVALUE, 10);
    emerald->setProperty(P_SIZE, 2);
    emerald->moveTo(g.getObject(ObjectIds::BUOY));
    g.registerObject(ObjectIds::EMERALD, std::move(emerald));
    
    // Create PAINTING (Painting - special treasure that can be taken from wall, has back side)
    auto painting = std::make_unique<ZObject>(ObjectIds::PAINTING, "painting");
    painting->addSynonym("painting");
    painting->addSynonym("picture");
    painting->addSynonym("art");
    painting->addSynonym("canvas");
    painting->addSynonym("treasure");
    painting->addAdjective("beautiful");
    painting->setFlag(ObjectFlag::TAKEBIT);
    painting->setFlag(ObjectFlag::BURNBIT);  // Can be burned (destroys value)
    painting->setProperty(P_VALUE, 4);
    painting->setProperty(P_TVALUE, 6);
    painting->setProperty(P_SIZE, 15);
    painting->setAction(paintingAction);
    painting->setFirstDesc("Fortunately, there is still one chance for you to be a vandal, for on the far wall is a painting of unparalleled beauty.");
    painting->setLongDesc("A painting by a neglected genius is here.");
    painting->moveTo(g.getObject(RoomIds::GALLERY));
    g.registerObject(ObjectIds::PAINTING, std::move(painting));
    
    // Create COFFIN (Gold coffin - both treasure and container)
    auto coffin = std::make_unique<ZObject>(ObjectIds::COFFIN, "gold coffin");
    coffin->addSynonym("coffin");
    coffin->addSynonym("casket");
    coffin->addSynonym("treasure");
    coffin->addAdjective("solid");
    coffin->addAdjective("gold");
    coffin->addAdjective("golden");
    coffin->addAdjective("egyptian");
    coffin->setFlag(ObjectFlag::TAKEBIT);
    coffin->setFlag(ObjectFlag::CONTBIT);
    coffin->setFlag(ObjectFlag::SACREDBIT);
    coffin->setFlag(ObjectFlag::SEARCHBIT);
    coffin->setProperty(P_VALUE, 10);
    coffin->setProperty(P_TVALUE, 15);
    coffin->setProperty(P_SIZE, 55);
    coffin->setProperty(P_CAPACITY, 35);
    coffin->setAction(coffinAction);
    coffin->setLongDesc("The solid-gold coffin used for the burial of Ramses II is here.");
    coffin->moveTo(g.getObject(RoomIds::EGYPT_ROOM));
    g.registerObject(ObjectIds::COFFIN, std::move(coffin));
    
    // Create JADE (Jade figurine)
    auto jade = std::make_unique<ZObject>(ObjectIds::JADE, "jade figurine");
    jade->addSynonym("figurine");
    jade->addSynonym("jade");
    jade->addSynonym("statue");
    jade->addSynonym("treasure");
    jade->addAdjective("jade");
    jade->addAdjective("small");
    jade->setFlag(ObjectFlag::TAKEBIT);
    jade->setProperty(P_VALUE, 5);
    jade->setProperty(P_TVALUE, 5);
    jade->setProperty(P_SIZE, 10);
    jade->setLongDesc("There is an exquisite jade figurine here.");
    jade->moveTo(g.getObject(RoomIds::BAT_ROOM));
    g.registerObject(ObjectIds::JADE, std::move(jade));
    
    // Create BRACELET (Sapphire-encrusted bracelet)
    auto bracelet = std::make_unique<ZObject>(ObjectIds::BRACELET, "sapphire-encrusted bracelet");
    bracelet->addSynonym("bracelet");
    bracelet->addSynonym("sapphire");
    bracelet->addSynonym("treasure");
    bracelet->addAdjective("sapphire");
    bracelet->addAdjective("encrusted");
    bracelet->addAdjective("beautiful");
    bracelet->setFlag(ObjectFlag::TAKEBIT);
    bracelet->setProperty(P_VALUE, 5);
    bracelet->setProperty(P_TVALUE, 5);
    bracelet->setProperty(P_SIZE, 10);
    bracelet->moveTo(g.getObject(RoomIds::GAS_ROOM));
    g.registerObject(ObjectIds::BRACELET, std::move(bracelet));
    
    // Create BAR (Platinum bar)
    auto bar = std::make_unique<ZObject>(ObjectIds::BAR, "platinum bar");
    bar->addSynonym("bar");
    bar->addSynonym("platinum");
    bar->addSynonym("treasure");
    bar->addAdjective("platinum");
    bar->addAdjective("large");
    bar->addAdjective("heavy");
    bar->setFlag(ObjectFlag::TAKEBIT);
    bar->setFlag(ObjectFlag::SACREDBIT);
    bar->setProperty(P_VALUE, 10);
    bar->setProperty(P_TVALUE, 5);
    bar->setProperty(P_SIZE, 20);
    bar->setLongDesc("On the ground is a large platinum bar.");
    bar->moveTo(g.getObject(RoomIds::LOUD_ROOM));
    g.registerObject(ObjectIds::BAR, std::move(bar));
    
    // Create POT_OF_GOLD (Pot of gold)
    auto potOfGold = std::make_unique<ZObject>(ObjectIds::POT_OF_GOLD, "pot of gold");
    potOfGold->addSynonym("pot");
    potOfGold->addSynonym("gold");
    potOfGold->addSynonym("treasure");
    potOfGold->addAdjective("gold");
    potOfGold->addAdjective("golden");
    potOfGold->addAdjective("large");
    potOfGold->setFlag(ObjectFlag::TAKEBIT);
    potOfGold->setFlag(ObjectFlag::INVISIBLE);
    potOfGold->setProperty(P_VALUE, 10);
    potOfGold->setProperty(P_TVALUE, 10);
    potOfGold->setProperty(P_SIZE, 15);
    potOfGold->moveTo(g.getObject(RoomIds::END_OF_RAINBOW));
    g.registerObject(ObjectIds::POT_OF_GOLD, std::move(potOfGold));
    
    // Create SCARAB (Scarab)
    auto scarab = std::make_unique<ZObject>(ObjectIds::SCARAB, "jewel-encrusted scarab");
    scarab->addSynonym("scarab");
    scarab->addSynonym("beetle");
    scarab->addSynonym("treasure");
    scarab->addAdjective("jewel");
    scarab->addAdjective("jeweled");
    scarab->addAdjective("encrusted");
    scarab->addAdjective("beautiful");
    scarab->addAdjective("ancient");
    scarab->setFlag(ObjectFlag::TAKEBIT);
    scarab->setFlag(ObjectFlag::INVISIBLE);
    scarab->setProperty(P_VALUE, 5);
    scarab->setProperty(P_TVALUE, 5);
    scarab->setProperty(P_SIZE, 8);
    scarab->moveTo(g.getObject(RoomIds::SANDY_CAVE));
    g.registerObject(ObjectIds::SCARAB, std::move(scarab));
    
    // Create TORCH (Ivory torch - also a light source)
    auto torch = std::make_unique<ZObject>(ObjectIds::TORCH, "ivory torch");
    torch->addSynonym("torch");
    torch->addSynonym("treasure");
    torch->addAdjective("ivory");
    torch->setFlag(ObjectFlag::TAKEBIT);
    torch->setFlag(ObjectFlag::LIGHTBIT);
    torch->setFlag(ObjectFlag::ONBIT);
    torch->setFlag(ObjectFlag::FLAMEBIT);
    torch->setProperty(P_VALUE, 14);
    torch->setProperty(P_TVALUE, 6);
    torch->setProperty(P_SIZE, 20);
    torch->setProperty(P_STRENGTH, 30);  // Fuel remaining (0-30)
    torch->setAction(torchAction);
    torch->moveTo(g.getObject(ObjectIds::PEDESTAL));
    g.registerObject(ObjectIds::TORCH, std::move(torch));
    
    // Create SCEPTRE (Egyptian sceptre - also a weapon)
    auto sceptre = std::make_unique<ZObject>(ObjectIds::SCEPTRE, "sceptre");
    sceptre->addSynonym("sceptre");
    sceptre->addSynonym("scepter");
    sceptre->addSynonym("treasure");
    sceptre->addAdjective("egyptian");
    sceptre->addAdjective("gold");
    sceptre->setFlag(ObjectFlag::TAKEBIT);
    sceptre->setFlag(ObjectFlag::WEAPONBIT);
    sceptre->setProperty(P_VALUE, 4);
    sceptre->setProperty(P_TVALUE, 6);
    sceptre->setProperty(P_SIZE, 3);
    sceptre->setLongDesc("An ornamented sceptre, tapering to a sharp point, is here.");
    sceptre->moveTo(g.getObject(ObjectIds::COFFIN));
    g.registerObject(ObjectIds::SCEPTRE, std::move(sceptre));
    
    // Create SKULL (Crystal skull)
    auto skull = std::make_unique<ZObject>(ObjectIds::SKULL, "crystal skull");
    skull->addSynonym("skull");
    skull->addSynonym("head");
    skull->addSynonym("treasure");
    skull->addAdjective("crystal");
    skull->setFlag(ObjectFlag::TAKEBIT);
    skull->setProperty(P_VALUE, 10);
    skull->setProperty(P_TVALUE, 10);
    skull->setProperty(P_SIZE, 15);
    skull->setLongDesc("Lying in one corner of the room is a beautifully carved crystal skull. It appears to be grinning at you rather nastily.");
    skull->moveTo(g.getObject(RoomIds::LAND_OF_LIVING_DEAD));
    g.registerObject(ObjectIds::SKULL, std::move(skull));
    
    // CANARY and BAUBLE are created earlier with the egg-related objects
    
    // ===== TOOL OBJECTS =====
    
    // Create SWORD (Elvish sword - weapon that glows near enemies)
    auto sword = std::make_unique<ZObject>(ObjectIds::SWORD, "sword");
    sword->addSynonym("sword");
    sword->addSynonym("blade");
    sword->addSynonym("orcrist");
    sword->addSynonym("glamdring");
    sword->addAdjective("elvish");
    sword->addAdjective("elven");
    sword->addAdjective("old");
    sword->addAdjective("antique");
    sword->setFlag(ObjectFlag::TAKEBIT);
    sword->setFlag(ObjectFlag::WEAPONBIT);
    sword->setProperty(P_SIZE, 30);
    sword->setProperty(P_STRENGTH, 10);  // High weapon effectiveness
    sword->setAction(swordAction);
    sword->moveTo(g.getObject(RoomIds::LIVING_ROOM));
    g.registerObject(ObjectIds::SWORD, std::move(sword));
    
    // Create KNIFE (Nasty knife - weapon, less effective than sword)
    auto knife = std::make_unique<ZObject>(ObjectIds::KNIFE, "nasty knife");
    knife->addSynonym("knife");
    knife->addSynonym("knives");
    knife->addSynonym("blade");
    knife->addAdjective("nasty");
    knife->addAdjective("sharp");
    knife->setFlag(ObjectFlag::TAKEBIT);
    knife->setFlag(ObjectFlag::WEAPONBIT);
    knife->setProperty(P_SIZE, 10);
    knife->setProperty(P_STRENGTH, 5);  // Medium weapon effectiveness
    knife->moveTo(g.getObject(RoomIds::ATTIC));
    g.registerObject(ObjectIds::KNIFE, std::move(knife));
    
    // Create LAMP (Battery-powered brass lantern - light source)
    auto lamp = std::make_unique<ZObject>(ObjectIds::LAMP, "brass lantern");
    lamp->addSynonym("lamp");
    lamp->addSynonym("lantern");
    lamp->addSynonym("light");
    lamp->addAdjective("brass");
    lamp->addAdjective("battery");
    lamp->setFlag(ObjectFlag::TAKEBIT);
    lamp->setFlag(ObjectFlag::LIGHTBIT);
    // Lamp starts off - player must turn it on
    lamp->setProperty(P_SIZE, 15);
    lamp->setProperty(P_CAPACITY, 330);  // Battery level - about 330 turns of light
    lamp->setProperty(P_STRENGTH, 100);  // Weapon strength if used as weapon
    lamp->setAction(lampAction);
    lamp->setLongDesc("There is a brass lantern (battery-powered) here.");
    lamp->moveTo(g.getObject(RoomIds::LIVING_ROOM));
    g.registerObject(ObjectIds::LAMP, std::move(lamp));
    
    // Create CANDLES (Pair of candles - temporary light source)
    auto candles = std::make_unique<ZObject>(ObjectIds::CANDLES, "pair of candles");
    candles->addSynonym("candles");
    candles->addSynonym("candle");
    candles->addSynonym("pair");
    candles->addAdjective("burning");
    candles->addAdjective("wax");
    candles->setFlag(ObjectFlag::TAKEBIT);
    candles->setFlag(ObjectFlag::LIGHTBIT);
    candles->setFlag(ObjectFlag::ONBIT);  // Candles start lit
    candles->setFlag(ObjectFlag::FLAMEBIT);
    candles->setProperty(P_SIZE, 10);
    candles->setProperty(P_STRENGTH, 50);  // Wax remaining (0-50)
    candles->setAction(candlesAction);
    candles->moveTo(g.getObject(RoomIds::SOUTH_TEMPLE));
    g.registerObject(ObjectIds::CANDLES, std::move(candles));
    
    // Create MATCH (Matchbook - one-time use light source)
    auto match = std::make_unique<ZObject>(ObjectIds::MATCH, "matchbook");
    match->addSynonym("match");
    match->addSynonym("matches");
    match->addSynonym("matchbook");
    match->addAdjective("match");
    match->setFlag(ObjectFlag::TAKEBIT);
    match->setProperty(P_SIZE, 2);
    match->setProperty(P_STRENGTH, 5);  // Number of matches remaining
    match->setAction(matchesAction);
    match->setLongDesc("There is a matchbook whose cover says \"Visit Beautiful FCD#3\" here.");
    match->moveTo(g.getObject(RoomIds::DAM_LOBBY));
    g.registerObject(ObjectIds::MATCH, std::move(match));
    
    // Create ROPE (Large coil of rope - for climbing and tying)
    auto rope = std::make_unique<ZObject>(ObjectIds::ROPE, "rope");
    rope->addSynonym("rope");
    rope->addSynonym("coil");
    rope->addSynonym("hemp");
    rope->addAdjective("large");
    rope->addAdjective("thick");
    rope->setFlag(ObjectFlag::TAKEBIT);
    rope->setProperty(P_SIZE, 10);
    rope->setAction(ropeAction);
    rope->moveTo(g.getObject(RoomIds::ATTIC));
    g.registerObject(ObjectIds::ROPE, std::move(rope));
    
    // Create WRENCH (Wrench - tool for bolts)
    auto wrench = std::make_unique<ZObject>(ObjectIds::WRENCH, "wrench");
    wrench->addSynonym("wrench");
    wrench->addSynonym("tool");
    wrench->addAdjective("metal");
    wrench->setFlag(ObjectFlag::TAKEBIT);
    wrench->setFlag(ObjectFlag::TOOLBIT);
    wrench->setProperty(P_SIZE, 10);
    wrench->setAction(wrenchAction);
    wrench->moveTo(g.getObject(RoomIds::MAINTENANCE_ROOM));
    g.registerObject(ObjectIds::WRENCH, std::move(wrench));
    
    // Create SCREWDRIVER (Screwdriver - tool for screws)
    auto screwdriver = std::make_unique<ZObject>(ObjectIds::SCREWDRIVER, "screwdriver");
    screwdriver->addSynonym("screwdriver");
    screwdriver->addSynonym("driver");
    screwdriver->addSynonym("tool");
    screwdriver->addAdjective("screw");
    screwdriver->setFlag(ObjectFlag::TAKEBIT);
    screwdriver->setFlag(ObjectFlag::TOOLBIT);
    screwdriver->setProperty(P_SIZE, 8);
    screwdriver->setAction(screwdriverAction);
    screwdriver->moveTo(g.getObject(RoomIds::MAINTENANCE_ROOM));
    g.registerObject(ObjectIds::SCREWDRIVER, std::move(screwdriver));
    
    // Create SHOVEL (Shovel - tool for digging)
    auto shovel = std::make_unique<ZObject>(ObjectIds::SHOVEL, "shovel");
    shovel->addSynonym("shovel");
    shovel->addSynonym("spade");
    shovel->addSynonym("tool");
    shovel->setFlag(ObjectFlag::TAKEBIT);
    shovel->setFlag(ObjectFlag::TOOLBIT);
    shovel->setProperty(P_SIZE, 15);
    shovel->setAction(shovelAction);
    shovel->moveTo(g.getObject(RoomIds::SANDY_BEACH));
    g.registerObject(ObjectIds::SHOVEL, std::move(shovel));
    
    // Create PUMP (Hand-held air pump - for inflating boat)
    auto pump = std::make_unique<ZObject>(ObjectIds::PUMP, "hand-held air pump");
    pump->addSynonym("pump");
    pump->addSynonym("air-pump");
    pump->addSynonym("tool");
    pump->addAdjective("hand-held");
    pump->addAdjective("small");
    pump->setFlag(ObjectFlag::TAKEBIT);
    pump->setFlag(ObjectFlag::TOOLBIT);
    pump->setProperty(P_SIZE, 8);
    pump->setAction(pumpAction);
    pump->moveTo(g.getObject(RoomIds::RESERVOIR_NORTH));
    g.registerObject(ObjectIds::PUMP, std::move(pump));
    

    // Create INFLATED_BOAT (Magic Boat)
    auto boatInflated = std::make_unique<ZObject>(ObjectIds::INFLATED_BOAT, "magic boat");
    boatInflated->addSynonym("boat");
    boatInflated->addSynonym("raft");
    boatInflated->addAdjective("rubber");
    boatInflated->addAdjective("inflated");
    boatInflated->addAdjective("small");
    boatInflated->setFlag(ObjectFlag::CONTBIT);    // Can hold player
    boatInflated->setFlag(ObjectFlag::VEHBIT);     // Is a vehicle
    boatInflated->setFlag(ObjectFlag::OPENBIT);    // Open container
    boatInflated->setProperty(P_SIZE, 50);
    boatInflated->setProperty(P_CAPACITY, 100);
    boatInflated->setAction(boatAction);
    // Starts not in game - created when inflatable boat is inflated
    g.registerObject(ObjectIds::BOAT_INFLATED, std::move(boatInflated));
    
    // Create BOAT_PUNCTURED (Punctured rubber boat)
    auto boatPunctured = std::make_unique<ZObject>(ObjectIds::BOAT_PUNCTURED, "punctured boat");
    boatPunctured->addSynonym("boat");
    boatPunctured->addSynonym("raft");
    boatPunctured->addAdjective("rubber");
    boatPunctured->addAdjective("punctured");
    boatPunctured->addAdjective("damaged");
    boatPunctured->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    boatPunctured->setProperty(P_SIZE, 30);
    boatPunctured->setAction(puncturedBoatAction);
    // Starts not in game - created if boat is punctured
    g.registerObject(ObjectIds::BOAT_PUNCTURED, std::move(boatPunctured));

    // Create BOAT_INFLATABLE (Pile of plastic / Deflated boat)
    // ZIL: INFLATABLE-BOAT in DAM-BASE
    auto boatInflatable = std::make_unique<ZObject>(ObjectIds::BOAT_INFLATABLE, "pile of plastic");
    boatInflatable->addSynonym("boat");
    boatInflatable->addSynonym("pile");
    boatInflatable->addSynonym("plastic");
    boatInflatable->addSynonym("valve");
    boatInflatable->addAdjective("plastic");
    boatInflatable->addAdjective("inflatable"); // "inflat" in ZIL
    boatInflatable->setFlag(ObjectFlag::TAKEBIT);
    boatInflatable->setFlag(ObjectFlag::BURNBIT);
    boatInflatable->setAction(inflatableBoatAction);
    boatInflatable->moveTo(g.getObject(RoomIds::DAM_BASE)); 
    g.registerObject(ObjectIds::BOAT_INFLATABLE, std::move(boatInflatable));
    
    // Create BOTTLE (Glass bottle - container and tool)
    auto bottle = std::make_unique<ZObject>(ObjectIds::BOTTLE, "glass bottle");
    bottle->addSynonym("bottle");
    bottle->addSynonym("container");
    bottle->addAdjective("glass");
    bottle->addAdjective("clear");
    bottle->setFlag(ObjectFlag::TAKEBIT);
    bottle->setFlag(ObjectFlag::CONTBIT);
    bottle->setFlag(ObjectFlag::TRANSBIT);  // Transparent
    bottle->setProperty(P_SIZE, 8);
    bottle->setProperty(P_CAPACITY, 4);
    bottle->setAction(bottleAction);
    bottle->setLongDesc("A bottle is sitting on the table.");
    bottle->moveTo(g.getObject(RoomIds::KITCHEN));
    g.registerObject(ObjectIds::BOTTLE, std::move(bottle));
    
    // Create WATER (Water in bottle)
    auto water = std::make_unique<ZObject>(ObjectIds::WATER, "quantity of water");
    water->addSynonym("water");
    water->addSynonym("quantity");
    water->addAdjective("clear");
    water->setFlag(ObjectFlag::TAKEBIT);
    water->setProperty(P_SIZE, 4);
    water->moveTo(g.getObject(ObjectIds::BOTTLE));  // Initially in bottle
    g.registerObject(ObjectIds::WATER, std::move(water));
    
    // ===== PUZZLE OBJECTS (Task 45) =====
    
    // Create MACHINE (Control panel puzzle)
    auto machine = std::make_unique<ZObject>(ObjectIds::MACHINE, "machine");
    machine->addSynonym("machine");
    machine->addSynonym("panel");
    machine->addSynonym("controls");
    machine->addSynonym("contraption");
    machine->addAdjective("control");
    machine->addAdjective("metal");
    machine->addAdjective("large");
    machine->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    machine->setFlag(ObjectFlag::CONTBIT);     // Can contain things
    machine->setProperty(P_SIZE, 100);
    machine->setProperty(P_CAPACITY, 20);
    machine->setAction(machineAction);
    machine->moveTo(g.getObject(RoomIds::MACHINE_ROOM));
    g.registerObject(ObjectIds::MACHINE, std::move(machine));
    
    // Create MIRROR_1 (First mirror)
    auto mirror1 = std::make_unique<ZObject>(ObjectIds::MIRROR_1, "mirror");
    mirror1->addSynonym("mirror");
    mirror1->addSynonym("glass");
    mirror1->addAdjective("large");
    mirror1->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    mirror1->setFlag(ObjectFlag::NDESCBIT);    // No automatic description
    mirror1->setAction(mirrorAction);
    mirror1->moveTo(g.getObject(RoomIds::MIRROR_ROOM_1));
    g.registerObject(ObjectIds::MIRROR_1, std::move(mirror1));
    
    // Create MIRROR_2 (Second mirror)
    auto mirror2 = std::make_unique<ZObject>(ObjectIds::MIRROR_2, "mirror");
    mirror2->addSynonym("mirror");
    mirror2->addSynonym("glass");
    mirror2->addAdjective("large");
    mirror2->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    mirror2->setFlag(ObjectFlag::NDESCBIT);    // No automatic description
    mirror2->setAction(mirrorAction);
    mirror2->moveTo(g.getObject(RoomIds::MIRROR_ROOM_2));
    g.registerObject(ObjectIds::MIRROR_2, std::move(mirror2));
    
    // Create DAM (Dam structure)
    auto dam = std::make_unique<ZObject>(ObjectIds::DAM, "dam");
    dam->addSynonym("dam");
    dam->addSynonym("structure");
    dam->addAdjective("concrete");
    dam->addAdjective("massive");
    dam->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    dam->setFlag(ObjectFlag::NDESCBIT);
    dam->setAction(damAction);
    dam->moveTo(g.getObject(RoomIds::DAM_ROOM));
    g.registerObject(ObjectIds::DAM, std::move(dam));
    
    // Create BOLT (Metal bolt for dam puzzle)
    auto bolt = std::make_unique<ZObject>(ObjectIds::BOLT, "bolt");
    bolt->addSynonym("bolt");
    bolt->addSynonym("nut");
    bolt->addAdjective("metal");
    bolt->addAdjective("large");
    bolt->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    bolt->setFlag(ObjectFlag::TURNBIT);     // Can be turned
    bolt->setAction(boltAction);
    bolt->moveTo(g.getObject(RoomIds::MAINTENANCE_ROOM));
    g.registerObject(ObjectIds::BOLT, std::move(bolt));
    
    // Create BUBBLE (Green bubble)
    auto bubble = std::make_unique<ZObject>(ObjectIds::BUBBLE, "bubble");
    bubble->addSynonym("bubble");
    bubble->addAdjective("green");
    bubble->addAdjective("large");
    bubble->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    bubble->setAction(bubbleAction);
    // Bubble starts not in game - appears in certain puzzle conditions
    g.registerObject(ObjectIds::BUBBLE, std::move(bubble));
    
    // Create BELL (Brass bell in North Temple - 1dungeon.zil:164-170)
    extern bool bellAction();
    auto bell = std::make_unique<ZObject>(ObjectIds::BELL, "brass bell");
    bell->addSynonym("bell");
    bell->addAdjective("small");
    bell->addAdjective("brass");
    bell->setFlag(ObjectFlag::TAKEBIT);
    bell->setAction(bellAction);
    bell->moveTo(g.getObject(RoomIds::NORTH_TEMPLE));
    g.registerObject(ObjectIds::BELL, std::move(bell));

    // Create HOT_BELL (Red hot brass bell - 1dungeon.zil:172-178)
    extern bool hotBellAction();
    auto hotBell = std::make_unique<ZObject>(ObjectIds::HOT_BELL, "red hot brass bell");
    hotBell->addSynonym("bell");
    hotBell->addAdjective("brass");
    hotBell->addAdjective("hot");
    hotBell->addAdjective("red");
    hotBell->addAdjective("small");
    hotBell->setFlag(ObjectFlag::TRYTAKEBIT);
    hotBell->setAction(hotBellAction);
    hotBell->setLongDesc("On the ground is a red hot bell.");
    g.registerObject(ObjectIds::HOT_BELL, std::move(hotBell));

    // Create GHOSTS (Spirits in Entrance to Hades - 1dungeon.zil:109-115)
    extern bool ghostsAction();
    auto ghosts = std::make_unique<ZObject>(ObjectIds::GHOSTS, "number of ghosts");
    ghosts->addSynonym("ghosts");
    ghosts->addSynonym("spirits");
    ghosts->addSynonym("fiends");
    ghosts->addSynonym("force");
    ghosts->addAdjective("invisible");
    ghosts->addAdjective("evil");
    ghosts->setFlag(ObjectFlag::ACTORBIT);
    ghosts->setFlag(ObjectFlag::NDESCBIT);
    ghosts->setAction(ghostsAction);
    ghosts->moveTo(g.getObject(RoomIds::ENTRANCE_TO_HADES));
    g.registerObject(ObjectIds::GHOSTS, std::move(ghosts));
    
    // Create YELLOW_BUTTON
    auto yellowButton = std::make_unique<ZObject>(ObjectIds::YELLOW_BUTTON, "yellow button");
    yellowButton->addSynonym("button");
    yellowButton->addAdjective("yellow");
    yellowButton->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    yellowButton->setAction(buttonAction);
    yellowButton->moveTo(g.getObject(RoomIds::MACHINE_ROOM));
    g.registerObject(ObjectIds::YELLOW_BUTTON, std::move(yellowButton));
    
    // Create BROWN_BUTTON
    auto brownButton = std::make_unique<ZObject>(ObjectIds::BROWN_BUTTON, "brown button");
    brownButton->addSynonym("button");
    brownButton->addAdjective("brown");
    brownButton->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    brownButton->setAction(buttonAction);
    brownButton->moveTo(g.getObject(RoomIds::MACHINE_ROOM));
    g.registerObject(ObjectIds::BROWN_BUTTON, std::move(brownButton));
    
    // Create RED_BUTTON
    auto redButton = std::make_unique<ZObject>(ObjectIds::RED_BUTTON, "red button");
    redButton->addSynonym("button");
    redButton->addAdjective("red");
    redButton->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    redButton->setAction(buttonAction);
    redButton->moveTo(g.getObject(RoomIds::MACHINE_ROOM));
    g.registerObject(ObjectIds::RED_BUTTON, std::move(redButton));
    
    // Create BLUE_BUTTON
    auto blueButton = std::make_unique<ZObject>(ObjectIds::BLUE_BUTTON, "blue button");
    blueButton->addSynonym("button");
    blueButton->addAdjective("blue");
    blueButton->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    blueButton->setAction(buttonAction);
    blueButton->moveTo(g.getObject(RoomIds::MACHINE_ROOM));
    g.registerObject(ObjectIds::BLUE_BUTTON, std::move(blueButton));
    
    // Create GUNK (Vitreous slag)
    auto gunk = std::make_unique<ZObject>(ObjectIds::GUNK, "vitreous slag");
    gunk->addSynonym("gunk");
    gunk->addSynonym("slag");
    gunk->addSynonym("pile");
    gunk->addAdjective("vitreous");
    gunk->addAdjective("glassy");
    gunk->setFlag(ObjectFlag::TRYTAKEBIT);  // Can't be taken
    gunk->setAction(gunkAction);
    gunk->moveTo(g.getObject(RoomIds::MACHINE_ROOM));
    g.registerObject(ObjectIds::GUNK, std::move(gunk));
    

    // ===== SCENERY OBJECTS =====
    
    // House Scenery - Task 21.1
    
    // WHITE_HOUSE and BOARD already exist - verified
    
    // Create WINDOW (Generic window)
    auto window = std::make_unique<ZObject>(ObjectIds::WINDOW, "window");
    window->addSynonym("window");
    window->addSynonym("windows");
    window->setFlag(ObjectFlag::TRYTAKEBIT);
    window->setFlag(ObjectFlag::NDESCBIT);
    g.registerObject(ObjectIds::WINDOW, std::move(window));
    
    // Create FRONT_DOOR (Front door of house - boarded)
    auto frontDoor = std::make_unique<ZObject>(ObjectIds::FRONT_DOOR, "front door");
    frontDoor->addSynonym("door");
    frontDoor->addAdjective("front");
    frontDoor->addAdjective("boarded");
    frontDoor->setFlag(ObjectFlag::TRYTAKEBIT);
    frontDoor->setFlag(ObjectFlag::NDESCBIT);
    frontDoor->setFlag(ObjectFlag::DOORBIT);
    g.registerObject(ObjectIds::FRONT_DOOR, std::move(frontDoor));
    
    // Create CHIMNEY (Chimney in kitchen)
    auto chimney = std::make_unique<ZObject>(ObjectIds::CHIMNEY, "chimney");
    chimney->addSynonym("chimney");
    chimney->addAdjective("dark");
    chimney->setFlag(ObjectFlag::TRYTAKEBIT);
    chimney->setFlag(ObjectFlag::NDESCBIT);
    chimney->moveTo(g.getObject(RoomIds::KITCHEN));
    g.registerObject(ObjectIds::CHIMNEY, std::move(chimney));
    
    // Natural Scenery - Task 21.2
    
    // TREE and FOREST already exist - verified
    
    // Create RIVER (Frigid River)
    auto river = std::make_unique<ZObject>(ObjectIds::RIVER, "river");
    river->addSynonym("river");
    river->addSynonym("stream");
    river->addSynonym("water");
    river->addAdjective("frigid");
    river->setFlag(ObjectFlag::TRYTAKEBIT);
    river->setFlag(ObjectFlag::NDESCBIT);
    g.registerObject(ObjectIds::RIVER, std::move(river));
    
    // Create RAINBOW (Rainbow at Aragain Falls)
    auto rainbow = std::make_unique<ZObject>(ObjectIds::RAINBOW, "rainbow");
    rainbow->addSynonym("rainbow");
    rainbow->addAdjective("beautiful");
    rainbow->setFlag(ObjectFlag::TRYTAKEBIT);
    rainbow->setFlag(ObjectFlag::NDESCBIT);
    rainbow->moveTo(g.getObject(RoomIds::CANYON_VIEW));
    g.registerObject(ObjectIds::RAINBOW, std::move(rainbow));
    
    // Create MOUNTAIN_RANGE (Mountains in distance)
    auto mountainRange = std::make_unique<ZObject>(ObjectIds::MOUNTAIN_RANGE, "mountain range");
    mountainRange->addSynonym("mountains");
    mountainRange->addSynonym("mountain");
    mountainRange->addSynonym("range");
    mountainRange->addAdjective("flathead");
    mountainRange->setFlag(ObjectFlag::TRYTAKEBIT);
    mountainRange->setFlag(ObjectFlag::NDESCBIT);
    g.registerObject(ObjectIds::MOUNTAIN_RANGE, std::move(mountainRange));
    
    // Interior Scenery - Task 21.3
    
    // Create RUG (Oriental rug in living room)
    auto rug = std::make_unique<ZObject>(ObjectIds::RUG, "oriental rug");
    rug->addSynonym("rug");
    rug->addSynonym("carpet");
    rug->addAdjective("oriental");
    rug->addAdjective("large");
    rug->setFlag(ObjectFlag::TRYTAKEBIT);
    rug->setFlag(ObjectFlag::NDESCBIT);
    rug->setAction(rugAction);
    rug->moveTo(g.getObject(RoomIds::LIVING_ROOM));
    g.registerObject(ObjectIds::RUG, std::move(rug));
    
    // ===== NPCs =====
    
    // Create THIEF NPC
    auto thief = std::make_unique<ZObject>(ObjectIds::THIEF, "thief");
    thief->addSynonym("thief");
    thief->addSynonym("robber");
    thief->addSynonym("burglar");
    thief->addAdjective("seedy");
    thief->addAdjective("sinister");
    thief->setFlag(ObjectFlag::FIGHTBIT);    // Hostile NPC
    thief->setFlag(ObjectFlag::ACTORBIT);    // Is an actor/NPC
    thief->setProperty(P_STRENGTH, 5);       // Combat strength
    // Thief action handler - handles combat interactions
    thief->setAction([]() {
        auto& g = Globals::instance();
        
        // Handle EXAMINE
        if (g.prsa == V_EXAMINE) {
            auto& state = NPCSystem::getThiefState();
            if (state.isAlive) {
                printLine("The thief is a seedy-looking individual with a large bag. He is armed with a stiletto.");
            } else {
                printLine("The thief lies dead on the ground.");
            }
            return RTRUE;
        }
        
        // Handle ATTACK/KILL - delegate to NPC combat system
        if (g.prsa == V_ATTACK) {
            return NPCSystem::thiefCombat() ? RTRUE : RFALSE;
        }
        
        // Handle GIVE - thief takes anything offered
        if (g.prsa == V_GIVE) {
            if (g.prsi && g.prsi->getId() == ObjectIds::THIEF) {
                ZObject* bag = NPCSystem::getThiefBag();
                if (bag && g.prso) {
                    g.prso->moveTo(bag);
                    printLine("The thief takes the " + g.prso->getDesc() + " and places it in his bag.");
                    return RTRUE;
                }
            }
        }
        
        return RFALSE;
    });
    thief->setLongDesc("There is a suspicious-looking individual, holding a large bag, leaning against one wall. He is armed with a deadly stiletto.");
    // Initial location varies - thief wanders. Start in MAZE_1 for now
    thief->moveTo(g.getObject(RoomIds::MAZE_1));
    g.registerObject(ObjectIds::THIEF, std::move(thief));
    
    // Create STILETTO (thief's weapon)
    auto stiletto = std::make_unique<ZObject>(ObjectIds::STILETTO, "stiletto");
    stiletto->addSynonym("stiletto");
    stiletto->addSynonym("knife");
    stiletto->addAdjective("nasty");
    stiletto->setFlag(ObjectFlag::TAKEBIT);
    stiletto->setFlag(ObjectFlag::WEAPONBIT);
    stiletto->setProperty(P_SIZE, 5);
    stiletto->setProperty(P_STRENGTH, 4);
    // Stiletto starts with thief (will be dropped when thief dies)
    stiletto->moveTo(g.getObject(ObjectIds::THIEF));
    g.registerObject(ObjectIds::STILETTO, std::move(stiletto));
    
    // Create TROLL's AXE
    auto axe = std::make_unique<ZObject>(ObjectIds::AXE, "bloody axe");
    axe->addSynonym("axe");
    axe->addAdjective("bloody");
    axe->addAdjective("troll's");
    // Axe is not takeable while troll is alive (troll is holding it)
    // TAKEBIT will be set when troll dies
    axe->setFlag(ObjectFlag::WEAPONBIT);
    axe->setFlag(ObjectFlag::TOOLBIT); // Required for OPEN X WITH Y syntax
    axe->setProperty(P_SIZE, 15);
    axe->setProperty(P_STRENGTH, 7);  // Strong weapon
    // Axe starts with troll (will be dropped when troll dies)
    // Initially placed in troll room but not takeable
    axe->moveTo(g.getObject(RoomIds::TROLL_ROOM));
    g.registerObject(ObjectIds::AXE, std::move(axe));
    
    // Create TROLL NPC
    auto troll = std::make_unique<ZObject>(ObjectIds::TROLL, "troll");
    troll->addSynonym("troll");
    troll->setFlag(ObjectFlag::FIGHTBIT);    // Hostile NPC
    troll->setFlag(ObjectFlag::ACTORBIT);    // Is an actor/NPC
    troll->setProperty(P_STRENGTH, 8);       // Stronger than thief
    // Add action handler for troll behavior (blocking, combat)
    troll->setAction(NPCSystem::trollAction);
    troll->setLongDesc("A nasty-looking troll, brandishing a bloody axe, blocks all passages out of the room.");
    // Located at Troll Room initially
    troll->moveTo(g.getObject(RoomIds::TROLL_ROOM));
    g.registerObject(ObjectIds::TROLL, std::move(troll));
    
    // Create CYCLOPS NPC
    auto cyclops = std::make_unique<ZObject>(ObjectIds::CYCLOPS, "cyclops");
    cyclops->addSynonym("cyclops");
    cyclops->addSynonym("giant");
    cyclops->addSynonym("monster");
    cyclops->addSynonym("creature");
    cyclops->setFlag(ObjectFlag::FIGHTBIT);    // Initially hostile
    cyclops->setFlag(ObjectFlag::ACTORBIT);    // Is an actor/NPC
    cyclops->setProperty(P_STRENGTH, 10);      // Very strong
    cyclops->setAction(NPCSystem::cyclopsAction);  // Action handler for cyclops behavior
    // Located at Cyclops Room initially
    cyclops->moveTo(g.getObject(RoomIds::CYCLOPS_ROOM));
    g.registerObject(ObjectIds::CYCLOPS, std::move(cyclops));
    
    // GRUE is created by GGlobals::initGlobalObjects (gglobals.zil:184-189).
    
    // ===== TASK 24.2: Verify all object placements =====
    // All objects have been placed in their initial locations above
    // Key placements verified:
    // - Mailbox at West of House (with leaflet inside)
    // - Trophy case in Living Room
    // - Lamp and sword in Living Room
    // - Knife and rope in Attic
    // - Sack in Kitchen
    // - Treasures distributed throughout the world
    // - NPCs in their starting locations (thief, troll, cyclops)
    // - Player (adventurer) at West of House
    
    // ===== TASK 24.3: Set initial flags =====
    // Initial flags have been set during object/room creation above
    // Key flags verified:
    // - ONBIT set for all naturally lit rooms (exterior, house interior, dam area)
    // - OPENBIT set for initially open containers (mailbox, trophy case)
    // - RLANDBIT set for all land rooms
    // - SACREDBIT set for safe areas (no combat)
    // - TAKEBIT set for all takeable objects
    // - TRYTAKEBIT set for anchored objects (mailbox, scenery)
    // - CONTBIT set for all containers
    // - FIGHTBIT set for hostile NPCs
    
    // Initialize game state variables
    g.lit = true;  // West of House is lit
    g.score = 0;
    g.moves = 0;
    
    // Initialize additional objects from missing_objects.cpp
    // (No longer needed - all objects now in refactored initialization)
    
    // Initialize scenery objects
    void initializeScenery(); // Forward declaration
    initializeScenery();
    
    // Initialize tool objects
    void initializeTools(); // Forward declaration
    initializeTools();
    
    // Initialize global objects from gglobals.zil
    GGlobals::initGlobalObjects(g);
}


